### ISSUE TITLE
about the install

### ISSUE THREAD

**Issue by yxliu0903** [yeahrmek/pylean#2]
After pip install git+https://github.com/yeahrmek/pylean，I import pylean，but it said: No module named 'pylean'

**Comment by yeahrmek** [comment]
It looks, like you install pylean in one environment and then try to import it in another environment. Are trying to use it jupyter notebook?

**Comment by yxliu0903** [comment]
The problem has been settled, thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeahrmek/pylean"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月1日(星期四) 下午4:02
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [yeahrmek/pylean] about the install (Issue #2)





 
It looks, like you install pylean in one environment and then try to import it in another environment. Are trying to use it jupyter notebook?
